name: sticker_keyboard
description: Sticker Keyboard for Flutter apps with simple setup, category tabs, and built‑in search/recents.
version: 0.1.0
homepage: https://blossomdiary.dev
repository: https://github.com/blossomdiary/sticker_keyboard

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.19.3"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # plugin:
  #   platforms:
  #     # some_platform:
  #     #   pluginClass: somePluginClass
  
